import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SSR PAGE',
  description: 'Generated by create next app',
};

function SSRPage() {
  return <div>SSRPage</div>;
}

export default SSRPage;
