import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {' '}
        <nav>
          <ul className="flex justify-center">
            <li className="px-4">
              <Link href="/">HOME</Link>
            </li>
            <li className="px-4">
              <Link href="/ssg">SSG</Link>
            </li>
            <li className="px-4">
              <Link href="/isr">ISR</Link>
            </li>
            <li className="px-4">
              <Link href="/ssr">SSR</Link>
            </li>
            <li className="px-4">
              <Link href="/csr">CSR</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
