import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SSG PAGE',
  description: 'Generated by create next app',
};

function SSGPage() {
  return <div>SSGPage</div>;
}

export default SSGPage;
