import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SSG PAGE',
  description: 'Generated by create next app',
};

// 갱신되지 않는다.
const SSGPage = async () => {
  const response = await fetch(`https://catfact.ninja/fact`, {
    cache: 'force-cache',
  });
  const { fact } = await response.json();

  https: return (
    <div>
      SSG Page<p>{fact}</p>
    </div>
  );
};

export default SSGPage;
