import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CSR PAGE',
  description: 'Generated by create next app',
};

export default function layout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
