import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'ISR PAGE',
  description: 'Generated by create next app',
};

function ISRPage() {
  return <div>ISRPage</div>;
}

export default ISRPage;
